forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', '4.1.0'
mod 'puppetlabs/apt'
mod 'alup/rbenv'
mod 'nginx', git: 'https://github.com/jfryman/puppet-nginx'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/mysql'
mod 'gini/cassandra', git: 'https://github.com/dcosson/puppet-cassandra.git'
mod 'apache', git: 'https://github.com/puppetlabs/puppetlabs-apache'
mod 'freighthop', path: 'local_modules/freighthop'
